# Site wide configuration

title: ""
description: ""
#if you modify locale please have a look at _data/messages.yml too
locale: es
language: "es"
#for meta name="author" :
author: CreaDev
keywords: creative development, web design

#Target date in UTC / GMT
countdown:
  theme: flat-colors
  year: 2016
  month: 8
  day: 03
  hour: 4
  minute: 0

# Site owner
owner:
  name: CreaDev.co
  url: http://creadev.co
  email: info@creadev.co
  twitter: creadev_co
  google-plus:
  instagram: creadev.co
  facebook: PokemonGoCaliOficial
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url: http://creadev.co
    caption:


# Jekyll configuration
sass:
  sass_dir: _scss
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
