# Site wide configuration

title: "Alimentos Org√°nicos"
description: "Semillas de vida"
#if you modify locale please have a look at _data/messages.yml too
locale: es
language: "es"
#for meta name="author" :
author: CreaDev
keywords: creative development, web design

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2016
  month: 5
  day: 10
  hour: 0
  minute: 0

# Site owner
owner:
  name: CreaDev
  email: info@creadev.co
  twitter: creadev_co
  google-plus:
  instagramm:
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url: http://alimentosorganicos.co
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
