# Site wide configuration

title: "Creative Development"
description: "Coming Soon to Cali"
#if you modify locale please have a look at _data/messages.yml too
locale: es
language: "es"
#for meta name="author" :
author: Juan Roa / Jessica Giraldo
keywords: creative development, web design

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2016
  month: 2
  day: 4
  hour: 0
  minute: 0

# Site owner
owner:
  name: Juan Roa / Jessica Giraldo
  email: contact@juanroa.me
  twitter: jroadev
  google-plus:
  instagramm:
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url: http://creadev.co
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
